export const Actions = {
    GET_PEOPLE_LIST_REQUEST: "GET_PEOPLE_LIST_REQUEST",
    GET_PEOPLE_LIST_SUCCESS: "GET_PEOPLE_LIST_SUCCESS",
    GET_PEOPLE_LIST_ERROR: "GET_PEOPLE_LIST_ERROR",
    REMOVE_PEOPLE_REQUEST: "REMOVE_PEOPLE_REQUEST",
    REMOVE_PEOPLE_SUCCESS: "REMOVE_PEOPLE_SUCCESS",
    REMOVE_PEOPLE_ERROR: "REMOVE_PEOPLE_ERROR",
    API_URL: 'https://testapi.io/api/raghulXander/api/task/v1/peoples'
}